<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-J833GHP" failures="1" tests="6" name="test" time="0.164" errors="0" timestamp="2022-01-06T15:51:19 CET">
  <testcase classname="test.Classtest1" name="Demo" time="0.025">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Classtest1.Demo(Classtest1.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Classtest2" name="LoginAPIcarLoan" time="0.01"/>
  <testcase classname="test.Classtest2" name="WebloginCarLoan" time="0.002"/>
  <testcase classname="test.Classtest4" name="LoginAPIcarLoan" time="0.002"/>
  <testcase classname="test.Classtest4" name="MobileLiginCarLoan" time="0.002"/>
  <testcase classname="test.Classtest4" name="WebloginCarLoan" time="0.002"/>
  <testcase classname="test.Classtest1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- test -->
